### ISSUE TITLE
Cannot integrate from HMI with 2022.4.b1

### ISSUE THREAD

**Issue by Spitfire69** [custom-components/nordpool#133]
## Version of the custom_component
0.0.4

## Homeassistant version
2022.4.b0

## Describe the bug
I can not integrate Nordpool since 2022.4.b0 actually

![image](https://user-images.githubusercontent.com/28536879/161244337-d66dd800-0ad1-4b8c-abda-11b07c147f30.png)

**Comment by tobbensoft** [comment]
I would like to add this as I think it's a part of the same problem.

```Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:678
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 12:38:36 (1 occurrences)
Last logged: 12:38:36

The system cannot restart because the configuration is not valid: Platform error sensor.nordpool - cannot import name 'contextfunction' from 'jinja2' (/usr/local/lib/python3.9/site-packages/jinja2/__init__.py)
```

```Logger: homeassistant.components.websocket_api.http.connection
Source: components/hassio/__init__.py:689
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 12:38:36 (1 occurrences)
Last logged: 12:38:36

[140011928048976] The system cannot restart because the configuration is not valid: Platform error sensor.nordpool - cannot import name 'contextfunction' from 'jinja2' (/usr/local/lib/python3.9/site-packages/jinja2/__init__.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 193, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1634, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1671, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 689, in async_handle_core_service
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Platform error sensor.nordpool - cannot import name 'contextfunction' from 'jinja2' (/usr/local/lib/python3.9/site-packages/jinja2/__init__.py)
```

**Comment by tobbensoft** [comment]
Seems to be fixed with https://github.com/custom-components/nordpool/pull/132

:)
