### ISSUE TITLE
Jinja error

### ISSUE THREAD

**Issue by solarhome** [custom-components/nordpool#139]
Hi,

I get an error like in the  Fix #131 #132.

I have the 0.0.5 version, Ubuntu 20.04.4 LTS, genome 3.36.8, Oracle Virtualbox.

Sorry for the large letters in the configuration.yaml

**My system is**
Version | core-2022.4.3
-- | --
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
User | root
Virtual Environment | false
Python Version | 3.9.9
Operating System Family | Linux
Operating System Version | 5.10.108
CPU Architecture | x86_64
Timezone | Europe/Helsinki

<h3>Home Assistant Supervisor</h3>
        

Host Operating System | Home Assistant OS 7.6
-- | --
Update Channel | stable
Supervisor Version | supervisor-2022.04.0
Docker Version | 20.10.9
Disk Total | 31.3 GB
Disk Used | 2.9 GB
Healthy | true
Supported | true
Board | ova
Supervisor API | ok
Version API | ok
Installed Add-ons | Samba share (9.5.1)

Home Assistant Supervisor
Host Operating System 	Home Assistant OS 7.6
Update Channel 	stable
Supervisor Version 	supervisor-2022.04.0
Docker Version 	20.10.9
Disk Total 	31.3 GB
Disk Used 	2.9 GB
Healthy 	true
Supported 	true
Board 	ova
Supervisor API 	ok
Version API 	ok
Installed Add-ons 	Samba share (9.5.1)

## Configuration

default_config:

# Text to speech
tts:
  - platform: google_translate

nordpool:

sensor:
  - platform: nordpool

    # Should the prices include vat? Default True
    VAT: True

    # What currency the api fetches the prices in
    # this is only need if you want a sensor in a non local currecy
    currency: "EUR"

    # Helper so you can set your "low" price
    # low_price = hour_price < average * low_price_cutoff
    low_price_cutoff: 0.95

    # What power regions your are interested in.
    # Possible values: "DK1", "DK2", "FI", "LT", "LV", "Oslo", "Kr.sand", "Bergen", "Molde", "Tr.heim", "Tromsø", "SE1", "SE2", "SE3","SE4", "SYS"
    region: "Kr.sand"

    # How many decimals to use in the display of the price
    precision: 3

    # What the price should be displayed in default
    # Possible values: MWh, kWh and W
    # default: kWh
    price_type: kWh

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

Add your logs here.

2022-04-13 21:44:10 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration nordpool which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-04-13 21:44:10 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration fmi which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-04-13 21:44:18 WARNING (MainThread) [homeassistant.config_entries] Config entry 'SolarNet Datalogger at 192.168.10.180' for fronius integration not ready yet: Connection to Fronius device failed at http://192.168.10.180/solar_api/GetAPIVersion.cgi.; Retrying in background
2022-04-13 21:50:55 ERROR (MainThread) [homeassistant.components.hassio] The system cannot restart because the configuration is not valid: Platform error sensor.nordpool - cannot import name 'contextfunction' from 'jinja2' (/usr/local/lib/python3.9/site-packages/jinja2/__init__.py)
2022-04-13 21:50:55 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140044671938368] The system cannot restart because the configuration is not valid: Platform error sensor.nordpool - cannot import name 'contextfunction' from 'jinja2' (/usr/local/lib/python3.9/site-packages/jinja2/__init__.py)
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 193, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1634, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1671, in _execute_service
await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 674, in async_handle_core_service
raise HomeAssistantError(homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Platform error sensor.nordpool - cannot import name 'contextfunction' from 'jinja2' (/usr/local/lib/python3.9/site-packages/jinja2/__init__.py)

## Describe the bug

Nordpool integration worked with my system about a week ago but then I updated HA and nordpool integration went broken. I had 0.0.4 then. I emptied that nordpool directory and copy pasted new 0.0.5 there but it does not start to work.

I have working integrations like FMI and Fronius datalogger.

## Debug log

```text

Add your logs here.

```

**Comment by Hellowlol** [comment]
You need to reinstall. it clearly isnt updated

**Comment by solarhome** [comment]
Thanks
