### ISSUE TITLE
Setup fails for 2022.5.b0

### ISSUE THREAD

**Issue by Skeletorjus** [custom-components/nordpool#143]
## Version of the custom_component

0.0.5

## Homeassistant version
2022.5.0b0

## Configuration

```yaml



```

## Describe the bug
Home Assistant throws an error while trying to setup the sensor,

## Debug log

```text

2022-04-27 21:49:15 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration nordpool: Unable to import component: cannot import name 'EVENT_TIME_CHANGED' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)

```

**Comment by Nordicfastware** [comment]
Same issue for me, on Beta 2022.5.0b0.
Traced back to this change made to the core for the beta: [https://github.com/home-assistant/core/pull/69643](url)

**Comment by paarak** [comment]
Same issue for me!
Home Assistant Core 2022.5.0b1
Home Assistant Supervisor 2022.04.4
Home Assistant OS 8.0.rc3
Kernel version 5.15.35
Agent version 1.2.1

**Comment by Klangen82** [comment]
Is there any plan to transition to the built-in event helpers? Sounds like a small change but I'm not a programmer:(  "in most cases, a one-line drop-in replacement"

https://developers.home-assistant.io/blog/2022/04/20/saying-goodbye-to-event_time_changed/

**Comment by Hellowlol** [comment]
I havnt had tine to investigate it. But I highly doubt we can just drop in replace it, as i have modified the code to support other timezones.

**Comment by Klangen82** [comment]
I believe you when you say that, as I said not a programmer:/ It's just that the integration will not work when they release 2022-05 version. You have UTC time changes so I guess this should work with times zones, but again that do I know. Please let me know if there is anything I can do or help and I will try my best.

![image](https://user-images.githubusercontent.com/25564168/166242627-79224b04-e359-41a3-93f0-45def0009f5f.png)

**Comment by Hellowlol** [comment]
Anybody want to test https://github.com/custom-components/nordpool/pull/145 ? This should work with the latest dev version

**Comment by Skeletorjus** [comment]
> Anybody want to test #145 ? This should work with the latest dev version

Maybe I did something wrong, but I couldn't get it to work.

```
2022-05-03 23:07:42 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.nordpool.config_flow
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 603, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 620, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/nordpool/__init__.py", line 17, in <module>    from .events import async_track_time_change_in_tz
  File "/config/custom_components/nordpool/events.py", line 31, in <module>
    action: Callable[[datetime], Awaitable[None] | None],
TypeError: unsupported operand type(s) for |: 'types.GenericAlias' and 'NoneType'
2022-05-03 23:07:42 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration nordpool: Exception importing custom_components.nordpool.config_flow
```

**Comment by aherbjornsen** [comment]
It would be easier for me to test this if it showed up as a beta version in HACS.

I manually copied the 4 changed files from 0.0.6 and got the same error as Skeletorjus.

**Comment by Klangen82** [comment]
Same here, I tested with HA version 2022.5.0b7.

**Comment by KennethSeiero** [comment]
Same here, this is no longer just the beta version. I'm on the official branch, and my nordpool just stopped working after 2022.5.0 update

**Comment by Hellowlol** [comment]
That's strange, that typing signature is copied directly from homeassistant and works fine in my dev docker. What python version are you running?

**Comment by Klangen82** [comment]
Thanks @Hellowlol for fixing this :)
