### ISSUE TITLE
Nordpool integration broken after upgrade to HA 2022.7.X

### ISSUE THREAD

**Issue by AseKarlsson** [custom-components/nordpool#167]
Hi,

Your integration only shows NaN after upgrading to HA 2022.7.X.
Is this related to the new version on Python in this release?

//Ase

**Comment by Hellowlol** [comment]
I havnt updated yet so i don’t know. Can you post the errors in the 🪵?

**Comment by AseKarlsson** [comment]
Hi Steffen,
Seems to be a lot of errors related to Python:

Logger: homeassistant.components.sensor
Source: custom_components/nordpool/aio_price.py:151
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 6:16:22 PM (2 occurrences)
Last logged: 6:16:22 PM
•	Error adding entities for domain sensor with platform nordpool
•	Error while setting up nordpool platform for sensor
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1154, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1154, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1154, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 867, in _resolve_host
    await event.wait()
  File "/usr/local/lib/python3.10/site-packages/aiohttp/locks.py", line 34, in wait
    raise self._exc
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 867, in _resolve_host
    await event.wait()
  File "/usr/local/lib/python3.10/site-packages/aiohttp/locks.py", line 34, in wait
    raise self._exc
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 880, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 860, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 397, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 641, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 775, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/nordpool/sensor.py", line 484, in async_added_to_hass
    await self.check_stuff()
  File "/config/custom_components/nordpool/sensor.py", line 442, in check_stuff
    today = await self._api.today(self._area, self._currency)
  File "/config/custom_components/nordpool/__init__.py", line 106, in today
    res = await self._someday(area, currency, "today")
  File "/config/custom_components/nordpool/__init__.py", line 96, in _someday
    await self.update_today(None)
  File "/config/custom_components/nordpool/__init__.py", line 77, in update_today
    await self._update("today")
  File "/config/custom_components/nordpool/__init__.py", line 68, in _update
    data = await spot.hourly(end_date=dt)
  File "/config/custom_components/nordpool/aio_price.py", line 255, in hourly
    return await self.fetch(self.HOURLY, end_date, areas)
  File "/config/custom_components/nordpool/aio_price.py", line 248, in fetch
    res = await asyncio.gather(*jobs)
  File "/config/custom_components/nordpool/aio_price.py", line 165, in _fetch_json
    return await self._io(
  File "/config/custom_components/nordpool/aio_price.py", line 151, in _io
    resp = await self.client.get(url, params=kwargs)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host www.nordpoolgroup.com:443 ssl:default [Try again]

**Comment by AseKarlsson** [comment]
Hi Steffen,

Seems it started working with HA 2022.7.3
