### ISSUE TITLE
Integration failed to get data

### ISSUE THREAD

**Issue by bj00rn** [custom-components/nordpool#184]
## Version of the custom_component

0.0.7 from HACS
## Homeassistant version
2022.3.2

## Configuration

```yaml

Add your configuration here.

```

## Describe the bug

Integration failed to get data. Reloading the integration fixed the problem.

## Debug log

```text

Logger: homeassistant.util.logging
Source: util/logging.py:114
First occurred: 17 augusti 2022 00:00:22 (49 occurrences)
Last logged: 22:00:00

Exception in check_stuff when dispatching 'nordpool_update': () Traceback (most recent call last): File "/config/custom_components/nordpool/sensor.py", line 469, in check_stuff await self._update_current_price() File "/config/custom_components/nordpool/sensor.py", line 422, in _update_current_price data = await self._api.today(self._area, self._currency) File "/config/custom_components/nordpool/__init__.py", line 106, in today res = await self._someday(area, currency, "today") File "/config/custom_components/nordpool/__init__.py", line 99, in _someday return self._data.get(currency, {}).get(day, {}).get(area) AttributeError: 'NoneType' object has no attribute 'get'

```

**Comment by Hellowlol** [comment]
Hi @bj00rn 

This is just the traceback. Please provide a debug log next time as I don't have enough info to create the issue.
