### ISSUE TITLE
Sensor stopped working - State "unknown"

### ISSUE THREAD

**Issue by michaelpiron** [custom-components/nordpool#194]
## Version of the custom_component
v0.0.7 installed via HACS

## Homeassistant version
 Home Assistant 2022.9.2 
Supervisor 2022.08.6 
Operating System 8.5 
Frontend 20220907.0 - latest 

## Configuration
Installed via UI.
Configured this sensor: nordpool_kwh_be_eur_3_10_021

## Describe the bug
Since yesterday, the integration stopped working: the entity turned to status "Unknown"
However: information for tomorrow is provided.
![image](https://user-images.githubusercontent.com/4469877/189672426-96d88327-a837-4b5f-a6f5-e352b00d2954.png)

## Debug log

```Logger: homeassistant.components.sensor
Source: custom_components/nordpool/aio_price.py:250
Integration: Sensor (documentation, issues)
First occurred: 12:48:41 (2 occurrences)
Last logged: 12:48:41

Error adding entities for domain sensor with platform nordpool
Error while setting up nordpool platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 691, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 776, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/nordpool/sensor.py", line 484, in async_added_to_hass
    await self.check_stuff()
  File "/config/custom_components/nordpool/sensor.py", line 442, in check_stuff
    today = await self._api.today(self._area, self._currency)
  File "/config/custom_components/nordpool/__init__.py", line 106, in today
    res = await self._someday(area, currency, "today")
  File "/config/custom_components/nordpool/__init__.py", line 96, in _someday
    await self.update_today(None)
  File "/config/custom_components/nordpool/__init__.py", line 77, in update_today
    await self._update("today")
  File "/config/custom_components/nordpool/__init__.py", line 68, in _update
    data = await spot.hourly(end_date=dt)
  File "/config/custom_components/nordpool/aio_price.py", line 255, in hourly
    return await self.fetch(self.HOURLY, end_date, areas)
  File "/config/custom_components/nordpool/aio_price.py", line 250, in fetch
    raw = [self._parse_json(i, areas) for i in res]
  File "/config/custom_components/nordpool/aio_price.py", line 250, in <listcomp>
    raw = [self._parse_json(i, areas) for i in res]
  File "/usr/local/lib/python3.10/site-packages/nordpool/elspot.py", line 37, in _parse_json
    currency = data['currency']
KeyError: 'currency'

```

**Comment by Hellowlol** [comment]
Reload the sensor. Seems it was uncomplete data from nordpool

**Comment by hedumor** [comment]
Hi, Seems to be broken now. Reload/restart not fixing this issue. Nordpool side did something?

**Comment by Hellowlol** [comment]
I still have data. Remove and add the sensors again.
