### ISSUE TITLE
Error adding entities for domain sensor with platform nordpool

### ISSUE THREAD

**Issue by martinarva** [custom-components/nordpool#204]
## Version of the custom_component

Latest

## Homeassistant version

Latest

## Configuration

```yaml

Configuration was done in UI

```

## Describe the bug

After restart Nordpool was starting very long and eventually failed

## Debug log

```Logger: homeassistant.components.sensor
Source: helpers/aiohttp_client.py:52
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 3:09:00 PM (2 occurrences)
Last logged: 3:09:00 PM

Error adding entities for domain sensor with platform nordpool
Error while setting up nordpool platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 691, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 776, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/nordpool/sensor.py", line 484, in async_added_to_hass
    await self.check_stuff()
  File "/config/custom_components/nordpool/sensor.py", line 442, in check_stuff
    today = await self._api.today(self._area, self._currency)
  File "/config/custom_components/nordpool/__init__.py", line 106, in today
    res = await self._someday(area, currency, "today")
  File "/config/custom_components/nordpool/__init__.py", line 96, in _someday
    await self.update_today(None)
  File "/config/custom_components/nordpool/__init__.py", line 77, in update_today
    await self._update("today")
  File "/config/custom_components/nordpool/__init__.py", line 68, in _update
    data = await spot.hourly(end_date=dt)
  File "/config/custom_components/nordpool/aio_price.py", line 255, in hourly
    return await self.fetch(self.HOURLY, end_date, areas)
  File "/config/custom_components/nordpool/aio_price.py", line 248, in fetch
    res = await asyncio.gather(*jobs)
  File "/config/custom_components/nordpool/aio_price.py", line 165, in _fetch_json
    return await self._io(
  File "/config/custom_components/nordpool/aio_price.py", line 154, in _io
    return await resp.json()
  File "/usr/src/homeassistant/homeassistant/helpers/aiohttp_client.py", line 52, in json
    return await super().json(*args, loads=loads, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://www.nordpoolgroup.com/api/marketdata/page/10?currency=EUR&endDate=14-10-2022')

```

**Comment by martinarva** [comment]
After 6th restart, it's working again.

**Comment by Hellowlol** [comment]
Mine stopped aswell. Seems like the api was broken. Reload solved the issue for me
