### ISSUE TITLE
Unable to fetch data since a week or more?

### ISSUE THREAD

**Issue by ways** [custom-components/nordpool#207]
## Version of the custom_component

0.0.7 from HACS

## Homeassistant version

Home Assistant 2022.10.4

## Configuration

```yaml
- platform: nordpool
  region: "Oslo"
  low_price_cutoff: 0.95
```

## Describe the bug

No data fetched from API.

## Debug log

```text

Oct 14 23:05:16 home-assistant hass[2922841]: 2022-10-14 23:05:16.076 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform n
ordpool                                                                                                                                                                           
Oct 14 23:05:16 home-assistant hass[2922841]: Traceback (most recent call last):                                                                                                  
Oct 14 23:05:16 home-assistant hass[2922841]:   File "/root/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities  
Oct 14 23:05:16 home-assistant hass[2922841]:     await asyncio.gather(*tasks)                                                                                                    
Oct 14 23:05:16 home-assistant hass[2922841]:   File "/root/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity_platform.py", line 691, in _async_add_entity   
Oct 14 23:05:16 home-assistant hass[2922841]:     await entity.add_to_platform_finish()                                                                                           
Oct 14 23:05:16 home-assistant hass[2922841]:   File "/root/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 776, in add_to_platform_finish       
Oct 14 23:05:16 home-assistant hass[2922841]:     await self.async_added_to_hass()                                                                              
Oct 14 23:05:16 home-assistant hass[2922841]:   File "/root/.homeassistant/custom_components/nordpool/sensor.py", line 484, in async_added_to_hass              
Oct 14 23:05:16 home-assistant hass[2922841]:     await self.check_stuff()                                                                                      
Oct 14 23:05:16 home-assistant hass[2922841]:   File "/root/.homeassistant/custom_components/nordpool/sensor.py", line 442, in check_stuff                      
Oct 14 23:05:16 home-assistant hass[2922841]:     today = await self._api.today(self._area, self._currency)                                                     
Oct 14 23:05:16 home-assistant hass[2922841]:   File "/root/.homeassistant/custom_components/nordpool/__init__.py", line 106, in today                          
Oct 14 23:05:16 home-assistant hass[2922841]:     res = await self._someday(area, currency, "today")                                                            
Oct 14 23:05:16 home-assistant hass[2922841]:   File "/root/.homeassistant/custom_components/nordpool/__init__.py", line 96, in _someday                        
Oct 14 23:05:16 home-assistant hass[2922841]:     await self.update_today(None)                                                                                 
Oct 14 23:05:16 home-assistant hass[2922841]:   File "/root/.homeassistant/custom_components/nordpool/__init__.py", line 77, in update_today                    
Oct 14 23:05:16 home-assistant hass[2922841]:     await self._update("today")                                                                                   
Oct 14 23:05:16 home-assistant hass[2922841]:   File "/root/.homeassistant/custom_components/nordpool/__init__.py", line 68, in _update                         
Oct 14 23:05:16 home-assistant hass[2922841]:     data = await spot.hourly(end_date=dt)                                                                         
Oct 14 23:05:16 home-assistant hass[2922841]:   File "/root/.homeassistant/custom_components/nordpool/aio_price.py", line 256, in hourly                        
Oct 14 23:05:16 home-assistant hass[2922841]:     return await self.fetch(self.HOURLY, end_date, areas)                                                         
Oct 14 23:05:16 home-assistant hass[2922841]:   File "/root/.homeassistant/custom_components/nordpool/aio_price.py", line 249, in fetch                         
Oct 14 23:05:16 home-assistant hass[2922841]:     res = await asyncio.gather(*jobs)                                                   
Oct 14 23:05:16 home-assistant hass[2922841]:   File "/root/.homeassistant/custom_components/nordpool/aio_price.py", line 166, in _fetch_json                   
Oct 14 23:05:16 home-assistant hass[2922841]:     return await self._io(                                                                                        
Oct 14 23:05:16 home-assistant hass[2922841]:   File "/root/.homeassistant/custom_components/nordpool/aio_price.py", line 155, in _io                           
Oct 14 23:05:16 home-assistant hass[2922841]:     return await resp.json(content_type='text/html')                                                              
Oct 14 23:05:16 home-assistant hass[2922841]:   File "/root/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/aiohttp_client.py", line 52, in json
Oct 14 23:05:16 home-assistant hass[2922841]:     return await super().json(*args, loads=loads, **kwargs)                              
Oct 14 23:05:16 home-assistant hass[2922841]:   File "/root/homeassistant/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1103, in json             
Oct 14 23:05:16 home-assistant hass[2922841]:     raise ContentTypeError(                                                                                       
Oct 14 23:05:16 home-assistant hass[2922841]: aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: application/json; charset=u
tf-8', url=URL('https://www.nordpoolgroup.com/api/marketdata/page/10?currency=NOK&endDate=14-10-2022')

```

**Comment by ways** [comment]
Never mind. Was because of change from https://github.com/custom-components/nordpool/issues/205
=)
