### ISSUE TITLE
Nordpool data not available after a day

### ISSUE THREAD

**Issue by MathieuWuyts** [custom-components/nordpool#208]
Logger: homeassistant.components.sensor
Source: custom_components/nordpool/aio_price.py:151
Integration: Sensor (documentation, issues)
First occurred: 08:56:50 (6 occurrences)
Last logged: 09:45:53

Error adding entities for domain sensor with platform nordpool
Error while setting up nordpool platform for sensor
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1154, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1154, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1154, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 867, in _resolve_host
    await event.wait()
  File "/usr/local/lib/python3.10/site-packages/aiohttp/locks.py", line 34, in wait
    raise self._exc
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 867, in _resolve_host
    await event.wait()
  File "/usr/local/lib/python3.10/site-packages/aiohttp/locks.py", line 34, in wait
    raise self._exc
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 880, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 860, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 691, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 776, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/nordpool/sensor.py", line 484, in async_added_to_hass
    await self.check_stuff()
  File "/config/custom_components/nordpool/sensor.py", line 442, in check_stuff
    today = await self._api.today(self._area, self._currency)
  File "/config/custom_components/nordpool/__init__.py", line 106, in today
    res = await self._someday(area, currency, "today")
  File "/config/custom_components/nordpool/__init__.py", line 96, in _someday
    await self.update_today(None)
  File "/config/custom_components/nordpool/__init__.py", line 77, in update_today
    await self._update("today")
  File "/config/custom_components/nordpool/__init__.py", line 68, in _update
    data = await spot.hourly(end_date=dt)
  File "/config/custom_components/nordpool/aio_price.py", line 255, in hourly
    return await self.fetch(self.HOURLY, end_date, areas)
  File "/config/custom_components/nordpool/aio_price.py", line 248, in fetch
    res = await asyncio.gather(*jobs)
  File "/config/custom_components/nordpool/aio_price.py", line 165, in _fetch_json
    return await self._io(
  File "/config/custom_components/nordpool/aio_price.py", line 151, in _io
    resp = await self.client.get(url, params=kwargs)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host www.nordpoolgroup.com:443 ssl:default [Try again]

**Comment by MathieuWuyts** [comment]
When I am able to add the sensor at a later time:
Deze fout is ontstaan door een aangepaste integratie.

Logger: homeassistant
Source: custom_components/nordpool/__init__.py:128
Integration: nordpool (documentation, issues)
First occurred: 18 oktober 2022 om 02:00:00 (1 occurrences)
Last logged: 18 oktober 2022 om 02:00:00

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/nordpool/__init__.py", line 128, in new_day_cb
    if not len(api._data[curr]["tomorrow"]):
KeyError: 'tomorrow'

**Comment by Hellowlol** [comment]
Closing as it seems related to a temporary issue with nordpools api
