### ISSUE TITLE
Nordpool changing their portal, will this integration work in 2024?

### ISSUE THREAD

**Issue by large** [custom-components/nordpool#361]
I believe they are shutting down their old system 01.01.2024 and replace it with https://data.nordpoolgroup.com

Anyone looked into this?

**Comment by Hellowlol** [comment]
No, this is new information for me. Where did you read this?

**Comment by large** [comment]
That is probably what is going to happen: https://www.nordpoolgroup.com/en/services/power-market-data-services/dataportal-launch-update/

Since the old data portal is what you see in their homepage today, it will probably be replaced by this new one.
Making the API that this integration (and many others) fetch data from offline/disable in 2024.

Making a grabber using "Angular" and a web-view is a whole other ball game.

**Comment by zagor** [comment]
Note that this is not just a system change, they are also introducing data access fees starting at €800/user/year:

https://www.nordpoolgroup.com/en/services/power-market-data-services/dataportalregistration/

**Comment by large** [comment]
We only need access to the exchange rates, because data is available at Entso-E.

**Comment by zagor** [comment]
Unfortunately ENTSO-E requires that every person to access their API requests a separate API key by emailing them. It takes a number of working days for them to manually(!) process each request. That is not a great experience for HomeAssistant end-users.

I found a site that republishes (some of) the ENTSO-E data without any login requirements, and with exchange rate handled: https://www.elprisetjustnu.se/api/

Unfortunately they publish a separate api for each geographical area, and don't seem to have apis for all areas. I'll email them and see if they are interested in publishing everything in a single place.

**Comment by jkaberg** [comment]
I'd just like to point out this resource aswell: https://spot.56k.guru/homeassistant -> https://github.com/Hexagon/spotweb (also based on ENTSO-e)

**Comment by ISO-B** [comment]
Just created account to ENTSO-e and requested API access by sending email. Received API token in 20 minutes.  I agree that having to request API access by email is not most end-user friendly solution, but if that guarantees reliable access to data I would be ready to do it. Also it wouldn't be probably too hard to give user option to use ENTSO-e or some other service, like those that @zagor mentioned, as long as format is same.

**Comment by LAPDragnet** [comment]
According to a source at Nordpool the used API is already deprecated and could stop working at any time.

**Comment by corove** [comment]
Has anyone found a new way to get these data? I mean, Nordpool is constantly crashing and i need to make new API connections all the time. Would be nice to continue using cost controlled automation both in Node Red and in HA generally, but if NordPool is cutting their free API, we need a good solution soon. :-)

**Comment by jkaberg** [comment]
> Has anyone found a new way to get these data? I mean, Nordpool is constantly crashing and i need to make new API connections all the time. Would be nice to continue using cost controlled automation both in Node Red and in HA generally, but if NordPool is cutting their free API, we need a good solution soon. :-)

https://github.com/JaccoR/hass-entso-e

**Comment by trollkarlen** [comment]
I think it died for me yesterday :(
I will look in to getting it from the open sources but still in the same format as this component:
> https://www.elprisetjustnu.se/api/v1/prices/2023/12-30_SE1.json
> https://www.hvakosterstrommen.no/api/v1/prices/2023/12-30_NO5.json
> https://www.elprisenligenu.dk/api/v1/prices/2023/12-30_DK2.json
> https://www.sahkonhintatanaan.fi/api/v1/prices/2023/12-30.json

**Comment by LAPDragnet** [comment]
I got a new release of Nordpool, 0.0.15, on Sunday via HACS. Installed it on Monday morning and it works fine:
https://github.com/custom-components/nordpool/releases
It has a new API integration:
https://github.com/custom-components/nordpool/pull/413

**Comment by LAPDragnet** [comment]
The new 0.0.15 version works very good for me too but one slight annoyance/quirk is still there although I not sure if it is by design from Nordpool ;-)
When the daily average is negative (as today Monday in SE3) and the price for the current hour is negative the value of "_price_percent_to_average_" gets strange. Right now the price is -0.11, the average is -1.13 and "_price_percent_to_average_" is  0.0975. To me that could be -1.13/-0.11 = 10.2 instead.
A minor issue though :-)

**Comment by bertgaster** [comment]
7-11-2024
Hi,

My Nordpool intergration stops working also. Restart did not help. I read that Norpool changed his API. 

Log:
Logboek: Error during setup of component nordpool

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 288, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/nordpool/__init__.py", line 197, in async_setup
    return await _dry_setup(hass, config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nordpool/__init__.py", line 179, in _dry_setup
    tz=await dt_utils.async_get_time_zone("Europe/Stockholm"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'homeassistant.util.dt' has no attribute 'async_get_time_zone'

<end log>

See also: https://www.nordpoolgroup.com/en/trading/Operational-Message-List/2024/05/market-data-api-v1-eol-migration-to-v2-20240508075500/

=> We would like to remind you that support for Market Data API v1 will officially end on June 30 (2024).

=> What are the major changes in API v2?
One of the major changes you’ll notice is that we have consolidated multiple endpoints into one with API v2. You can find the mapping for the endpoints in the FAQ [https://developers.nordpoolgroup.com/reference/data-faq].

See also: https://www.nordpoolgroup.com/en/services/power-market-data-services/dataportal-launch-update/
and https://github.com/custom-components/nordpool/discussions/408

Is there a new HACS integration of Nordpool available for NL?
