### ISSUE TITLE
Detected blocking call to open inside the event loop by custom integration 'nordpool' at custom_components/nordpool/aio_price.py

### ISSUE THREAD

**Issue by romlisrl** [custom-components/nordpool#387]
## Version of the custom_component
0.0.14

## Homeassistant version
2024.6.4

## Configuration
```
#homeassistant:
#  customize: !include customize.yaml

#logger:
#  default: info
#  logs:
#    homeassistant.components.scrape: debug

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
automation: !include automations.yaml
#camera: !include includes/camera.yaml
#device_tracker: !include includes/device_tracker.yaml
#ffmpeg:
command_line: !include includes/cmd_line.yaml
frontend:
  themes: !include_dir_merge_named themes
group: !include groups.yaml
http: !include includes/http.yaml
#input_boolean: !include includes/input_boolean.yaml
#input_datetime: !include includes/input_datetime.yaml
#input_select: !include includes/input_select.yaml
#input_text: !include includes/input_text.yaml
#input_number: !include includes/input_number.yaml
#media_player: !include includes/mediaplayer.yaml
#mqtt: !include includes/mqtt.yaml
mqtt: !include includes/mqtt_sensor.yaml
notify: !include includes/notify.yaml
recorder: !include includes/recorder.yaml
#remote: !include includes/remote.yaml
#samsungtv: !include includes/samsungtv.yaml.old
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include_dir_merge_list sensors
shell_command: !include includes/shell_commands.yaml
switch: !include includes/switches.yaml
telegram_bot: !include includes/telegram.yaml
template: !include includes/templates.yaml
#timer: !include includes/timer.yaml
#wake_on_lan:
#webostv: !include includes/webostv.yaml.old
# Text to speech
#tts:
#  - platform: google_translate
```

## Describe the bug

After upgrading HA to the version 2024.6.4 I'm noticed a lot of log messages of blocking call.
It's possible to clear the log, but after reload component obviously it's will appears again.
I'm not sure how critical it is, but anyway.

## Debug log

Logger: homeassistant.util.loop
Source: util/loop.py:84
First occurred: 10:03:46 (72 occurrences)
Last logged: 10:03:48

```
Detected blocking call to open inside the event loop by custom integration 'nordpool' at custom_components/nordpool/aio_price.py, line 110: zone = tz.gettz(zone) (offender: /usr/local/lib/python3.12/site-packages/dateutil/tz/tz.py, line 464: fileobj = open(fileobj, 'rb')), please create a bug report at https://github.com/custom-components/nordpool/issues Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 649, in async_add_entities await add_func(coros, entities, timeout) File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 600, in _async_add_entities await coro File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 914, in _async_add_entity await entity.add_to_platform_finish() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1354, in add_to_platform_finish await self.async_added_to_hass() File "/config/custom_components/nordpool/sensor.py", line 518, in async_added_to_hass await self.handle_new_hr() File "/config/custom_components/nordpool/sensor.py", line 480, in handle_new_hr today = await self._api.today(self._area, self._currency) File "/config/custom_components/nordpool/__init__.py", line 110, in today return await self._someday(area, currency, "today") File "/config/custom_components/nordpool/__init__.py", line 99, in _someday await self.update_today(None) File "/config/custom_components/nordpool/__init__.py", line 80, in update_today await self._update("today") File "/config/custom_components/nordpool/__init__.py", line 73, in _update data = await spot.hourly(end_date=dt) File "/config/custom_components/nordpool/aio_price.py", line 228, in hourly return await self.fetch(self.HOURLY, end_date, areas) File "/usr/local/lib/python3.12/site-packages/backoff/_async.py", line 151, in retry ret = await target(*args, **kwargs) File "/config/custom_components/nordpool/aio_price.py", line 222, in fetch return join_result_for_correct_time(raw, end_date) File "/config/custom_components/nordpool/aio_price.py", line 110, in join_result_for_correct_time zone = tz.gettz(zone)
Detected blocking call to open inside the event loop by custom integration 'nordpool' at custom_components/nordpool/aio_price.py, line 110: zone = tz.gettz(zone) (offender: /usr/local/lib/python3.12/site-packages/dateutil/tz/tz.py, line 464: fileobj = open(fileobj, 'rb')), please create a bug report at https://github.com/custom-components/nordpool/issues Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 649, in async_add_entities await add_func(coros, entities, timeout) File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 600, in _async_add_entities await coro File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 914, in _async_add_entity await entity.add_to_platform_finish() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1354, in add_to_platform_finish await self.async_added_to_hass() File "/config/custom_components/nordpool/sensor.py", line 518, in async_added_to_hass await self.handle_new_hr() File "/config/custom_components/nordpool/sensor.py", line 480, in handle_new_hr today = await self._api.today(self._area, self._currency) File "/config/custom_components/nordpool/__init__.py", line 110, in today return await self._someday(area, currency, "today") File "/config/custom_components/nordpool/__init__.py", line 100, in _someday await self.update_tomorrow(None) File "/config/custom_components/nordpool/__init__.py", line 85, in update_tomorrow await self._update(type_="tomorrow", dt=dt_utils.now() + timedelta(hours=24)) File "/config/custom_components/nordpool/__init__.py", line 73, in _update data = await spot.hourly(end_date=dt) File "/config/custom_components/nordpool/aio_price.py", line 228, in hourly return await self.fetch(self.HOURLY, end_date, areas) File "/usr/local/lib/python3.12/site-packages/backoff/_async.py", line 151, in retry ret = await target(*args, **kwargs) File "/config/custom_components/nordpool/aio_price.py", line 222, in fetch return join_result_for_correct_time(raw, end_date) File "/config/custom_components/nordpool/aio_price.py", line 110, in join_result_for_correct_time zone = tz.gettz(zone)
```

**Comment by romlisrl** [comment]
Duplicate, sorry.
