### ISSUE TITLE
Integration errors blocking system reboots

### ISSUE THREAD

**Issue by andiukas** [custom-components/nordpool#392]
Integration 0.0.15b0 errors cause the HA to fully start within 9 minutes after reboot. After disabling integration, the system reboots in a few seconds.

![Screenshot 2024-08-06 084915](https://github.com/user-attachments/assets/47f79bef-6425-4043-8505-6c8ac8841700)

**Comment by bnordli** [comment]
Same for me.

Readable logs
```
homeassistant    | 2024-08-10T09:14:13.577661218Z 2024-08-10 11:14:13.576 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open with args ('/usr/local/lib/python3.12/site-packages/pytz/zoneinfo/Africa/Abidjan', 'rb') inside the event loop by custom integration 'nordpool' at custom_components/nordpool/__init__.py, line 158: tz=timezone("Europe/Stockholm"), (offender: /usr/local/lib/python3.12/site-packages/pytz/__init__.py, line 108: return open(filename, 'rb')), please create a bug report at https://github.com/custom-components/nordpool/issues
homeassistant    | 2024-08-10T09:14:13.577736848Z For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open
homeassistant    | 2024-08-10T09:14:13.577763792Z Traceback (most recent call last):
homeassistant    | 2024-08-10T09:14:13.577788088Z   File "<frozen runpy>", line 198, in _run_module_as_main
homeassistant    | 2024-08-10T09:14:13.577812106Z   File "<frozen runpy>", line 88, in _run_code
homeassistant    | 2024-08-10T09:14:13.577835958Z   File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
homeassistant    | 2024-08-10T09:14:13.577860773Z     sys.exit(main())
homeassistant    | 2024-08-10T09:14:13.577884439Z   File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
homeassistant    | 2024-08-10T09:14:13.577907976Z     exit_code = runner.run(runtime_conf)
homeassistant    | 2024-08-10T09:14:13.577931050Z   File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
homeassistant    | 2024-08-10T09:14:13.577955235Z     return loop.run_until_complete(setup_and_run_hass(runtime_config))
homeassistant    | 2024-08-10T09:14:13.577978772Z   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
homeassistant    | 2024-08-10T09:14:13.578003346Z     self.run_forever()
homeassistant    | 2024-08-10T09:14:13.578026846Z   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
homeassistant    | 2024-08-10T09:14:13.578050957Z     self._run_once()
homeassistant    | 2024-08-10T09:14:13.578074327Z   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
homeassistant    | 2024-08-10T09:14:13.578097919Z     handle._run()
homeassistant    | 2024-08-10T09:14:13.578120530Z   File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
homeassistant    | 2024-08-10T09:14:13.578175826Z     self._context.run(self._callback, *self._args)
homeassistant    | 2024-08-10T09:14:13.578200493Z   File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 298, in async_setup_platform
homeassistant    | 2024-08-10T09:14:13.578223622Z     platform = await async_prepare_setup_platform(
homeassistant    | 2024-08-10T09:14:13.578247326Z   File "/usr/src/homeassistant/homeassistant/setup.py", line 552, in async_prepare_setup_platform
homeassistant    | 2024-08-10T09:14:13.578272418Z     ) and not await async_setup_component(hass, integration.domain, hass_config):
homeassistant    | 2024-08-10T09:14:13.578296863Z   File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component
homeassistant    | 2024-08-10T09:14:13.578326048Z     result = await _async_setup_component(hass, domain, config)
homeassistant    | 2024-08-10T09:14:13.578349881Z   File "/usr/src/homeassistant/homeassistant/setup.py", line 416, in _async_setup_component
homeassistant    | 2024-08-10T09:14:13.578372973Z     result = await task
homeassistant    | 2024-08-10T09:14:13.578395436Z   File "/config/custom_components/nordpool/__init__.py", line 176, in async_setup
homeassistant    | 2024-08-10T09:14:13.578417992Z     return await _dry_setup(hass, config)
homeassistant    | 2024-08-10T09:14:13.578440288Z   File "/config/custom_components/nordpool/__init__.py", line 158, in _dry_setup
homeassistant    | 2024-08-10T09:14:13.578463917Z     tz=timezone("Europe/Stockholm"),
homeassistant    | 2024-08-10T09:14:13.578486695Z 
homeassistant    | 2024-08-10T09:14:18.752417257Z 2024-08-10 11:14:18.751 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open with args ('/usr/share/zoneinfo/Europe/Stockholm', 'rb') inside the event loop by custom integration 'nordpool' at custom_components/nordpool/aio_price.py, line 110: zone = tz.gettz(zone) (offender: /usr/local/lib/python3.12/site-packages/dateutil/tz/tz.py, line 464: fileobj = open(fileobj, 'rb')), please create a bug report at https://github.com/custom-components/nordpool/issues
homeassistant    | 2024-08-10T09:14:18.752502312Z For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open
homeassistant    | 2024-08-10T09:14:18.752530405Z Traceback (most recent call last):
homeassistant    | 2024-08-10T09:14:18.752554645Z   File "<frozen runpy>", line 198, in _run_module_as_main
homeassistant    | 2024-08-10T09:14:18.752578479Z   File "<frozen runpy>", line 88, in _run_code
homeassistant    | 2024-08-10T09:14:18.752602571Z   File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
homeassistant    | 2024-08-10T09:14:18.752626534Z     sys.exit(main())
homeassistant    | 2024-08-10T09:14:18.752649108Z   File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
homeassistant    | 2024-08-10T09:14:18.752672608Z     exit_code = runner.run(runtime_conf)
homeassistant    | 2024-08-10T09:14:18.752695978Z   File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
homeassistant    | 2024-08-10T09:14:18.752719589Z     return loop.run_until_complete(setup_and_run_hass(runtime_config))
homeassistant    | 2024-08-10T09:14:18.752742552Z   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
homeassistant    | 2024-08-10T09:14:18.752766107Z     self.run_forever()
homeassistant    | 2024-08-10T09:14:18.752817940Z   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
homeassistant    | 2024-08-10T09:14:18.752842996Z     self._run_once()
homeassistant    | 2024-08-10T09:14:18.752865995Z   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
homeassistant    | 2024-08-10T09:14:18.752888958Z     handle._run()
homeassistant    | 2024-08-10T09:14:18.752911940Z   File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
homeassistant    | 2024-08-10T09:14:18.752935310Z     self._context.run(self._callback, *self._args)
homeassistant    | 2024-08-10T09:14:18.752958421Z   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 647, in async_add_entities
homeassistant    | 2024-08-10T09:14:18.752982272Z     await add_func(coros, entities, timeout)
homeassistant    | 2024-08-10T09:14:18.753005606Z   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 598, in _async_add_entities
homeassistant    | 2024-08-10T09:14:18.753029198Z     await coro
homeassistant    | 2024-08-10T09:14:18.753051716Z   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 912, in _async_add_entity
homeassistant    | 2024-08-10T09:14:18.753074939Z     await entity.add_to_platform_finish()
homeassistant    | 2024-08-10T09:14:18.753102475Z   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1365, in add_to_platform_finish
homeassistant    | 2024-08-10T09:14:18.753126790Z     await self.async_added_to_hass()
homeassistant    | 2024-08-10T09:14:18.753148957Z   File "/config/custom_components/nordpool/sensor.py", line 518, in async_added_to_hass
homeassistant    | 2024-08-10T09:14:18.753171568Z     await self.handle_new_hr()
homeassistant    | 2024-08-10T09:14:18.753193864Z   File "/config/custom_components/nordpool/sensor.py", line 480, in handle_new_hr
homeassistant    | 2024-08-10T09:14:18.753216697Z     today = await self._api.today(self._area, self._currency)
homeassistant    | 2024-08-10T09:14:18.753238993Z   File "/config/custom_components/nordpool/__init__.py", line 110, in today
homeassistant    | 2024-08-10T09:14:18.753261474Z     return await self._someday(area, currency, "today")
homeassistant    | 2024-08-10T09:14:18.753283956Z   File "/config/custom_components/nordpool/__init__.py", line 99, in _someday
homeassistant    | 2024-08-10T09:14:18.753306678Z     await self.update_today(None)
homeassistant    | 2024-08-10T09:14:18.753328474Z   File "/config/custom_components/nordpool/__init__.py", line 80, in update_today
homeassistant    | 2024-08-10T09:14:18.753350937Z     await self._update("today")
homeassistant    | 2024-08-10T09:14:18.753373289Z   File "/config/custom_components/nordpool/__init__.py", line 73, in _update
homeassistant    | 2024-08-10T09:14:18.753395992Z     data = await spot.hourly(end_date=dt)
homeassistant    | 2024-08-10T09:14:18.753417807Z   File "/config/custom_components/nordpool/aio_price.py", line 228, in hourly
homeassistant    | 2024-08-10T09:14:18.753440510Z     return await self.fetch(self.HOURLY, end_date, areas)
homeassistant    | 2024-08-10T09:14:18.753462825Z   File "/usr/local/lib/python3.12/site-packages/backoff/_async.py", line 151, in retry
homeassistant    | 2024-08-10T09:14:18.753485380Z     ret = await target(*args, **kwargs)
homeassistant    | 2024-08-10T09:14:18.753507565Z   File "/config/custom_components/nordpool/aio_price.py", line 222, in fetch
homeassistant    | 2024-08-10T09:14:18.753555491Z     return join_result_for_correct_time(raw, end_date)
homeassistant    | 2024-08-10T09:14:18.753580676Z   File "/config/custom_components/nordpool/aio_price.py", line 110, in join_result_for_correct_time
homeassistant    | 2024-08-10T09:14:18.753605083Z     zone = tz.gettz(zone)
```
Probably causing an infinite reboot loop of Home Assistant (running on ghcr.io/home-assistant/raspberrypi4-homeassistant:2024.8.0).

It works fine after reverting to 2024.7.1.

**Comment by Elespecia** [comment]
Same here, I temporarily disabled the component.

**Comment by Hellowlol** [comment]
Duplicate
