### ISSUE TITLE
Sensor data will jam after running 2 days near midnight

### ISSUE THREAD

**Issue by JaniAst** [custom-components/nordpool#42]
Hello

I had this issue now several times and  it always appears to happen near midnight. The sensor data will jam and not updating. After homeassistant reboot it will work again couple of days. After jam there is In log file every hour this error message:
2020-10-31 22:00:02 ERROR (MainThread) [homeassistant.util.logging] Exception in check_stuff when dispatching 'nordpool_update': ()
Traceback (most recent call last):
  File "/config/custom_components/nordpool/sensor.py", line 404, in check_stuff
    await self._update_current_price()
  File "/config/custom_components/nordpool/sensor.py", line 356, in _update_current_price
    data = await self._api.today(self._area, self._currency)
  File "/config/custom_components/nordpool/__init__.py", line 109, in today
    res = await self._someday(area, currency, "today")
  File "/config/custom_components/nordpool/__init__.py", line 102, in _someday
    return self._data.get(currency, {}).get(day, {}).get(area)
AttributeError: 'NoneType' object has no attribute 'get'

2020-10-31 23:00:00 ERROR (MainThread) [homeassistant.util.logging] Exception in check_stuff when dispatching 'nordpool_update': ()
Traceback (most recent call last):
  File "/config/custom_components/nordpool/sensor.py", line 404, in check_stuff
    await self._update_current_price()
  File "/config/custom_components/nordpool/sensor.py", line 356, in _update_current_price
    data = await self._api.today(self._area, self._currency)
  File "/config/custom_components/nordpool/__init__.py", line 109, in today
    res = await self._someday(area, currency, "today")
  File "/config/custom_components/nordpool/__init__.py", line 102, in _someday
    return self._data.get(currency, {}).get(day, {}).get(area)
AttributeError: 'NoneType' object has no attribute 'get'

System info:
Home Assistant 0.115.6

**Comment by Hellowlol** [comment]
I can you turn on debug log?. I can’t see any reason why self._data should be set to None

**Comment by JaniAst** [comment]
2020-11-01 21:00:00 DEBUG (MainThread) [custom_components.nordpool] Called new_hr callback
2020-11-01 21:00:00 DEBUG (MainThread) [custom_components.nordpool.sensor] called check_stuff
2020-11-01 21:00:00 DEBUG (MainThread) [custom_components.nordpool.sensor] Updated nordpool_kwh_fi_eur_3_40_024 _current_price 2.55
2020-11-01 21:59:27 DEBUG (MainThread) [custom_components.nordpool] Called new_day_cb callback
2020-11-01 21:59:27 DEBUG (MainThread) [custom_components.nordpool.sensor] called check_stuff
2020-11-01 22:00:00 DEBUG (MainThread) [custom_components.nordpool] Called new_hr callback
2020-11-01 22:00:00 DEBUG (MainThread) [custom_components.nordpool] Called new_day_cb callback
2020-11-01 22:00:00 DEBUG (MainThread) [custom_components.nordpool] Updating tomorrows prices.
2020-11-01 22:00:00 DEBUG (MainThread) [custom_components.nordpool] calling _update today None
2020-11-01 22:00:00 DEBUG (MainThread) [custom_components.nordpool.sensor] called check_stuff
2020-11-01 22:00:00 DEBUG (MainThread) [custom_components.nordpool.misc] Its a new day!
2020-11-01 22:00:00 DEBUG (MainThread) [custom_components.nordpool.sensor] Called _update setting attrs for the day
2020-11-01 22:00:00 DEBUG (MainThread) [custom_components.nordpool.sensor] Updated nordpool_kwh_fi_eur_3_40_024 _current_price 1.44
2020-11-01 22:00:01 DEBUG (MainThread) [custom_components.nordpool.aio_price] requested https://www.nordpoolgroup.com/api/marketdata/page/10?currency=EUR&endDate=01-11-2020 {'currency': 'EUR', 'endDate': '01-11-2020'}
2020-11-01 22:00:10 DEBUG (MainThread) [custom_components.nordpool.aio_price] requested https://www.nordpoolgroup.com/api/marketdata/page/10?currency=EUR&endDate=02-11-2020 {'currency': 'EUR', 'endDate': '02-11-2020'}
2020-11-01 22:00:11 DEBUG (MainThread) [custom_components.nordpool.aio_price] requested https://www.nordpoolgroup.com/api/marketdata/page/10?currency=EUR&endDate=31-10-2020 {'currency': 'EUR', 'endDate': '31-10-2020'}
2020-11-01 22:00:11 DEBUG (MainThread) [custom_components.nordpool.aio_price] join_result_for_correct_time 2020-11-02 00:00:00.002864+02:00
2020-11-01 22:00:11 DEBUG (MainThread) [custom_components.nordpool.aio_price] Skipping AT
2020-11-01 22:00:11 DEBUG (MainThread) [custom_components.nordpool.aio_price] Skipping BE
2020-11-01 22:00:11 DEBUG (MainThread) [custom_components.nordpool.aio_price] Skipping DE-LU
2020-11-01 22:00:11 DEBUG (MainThread) [custom_components.nordpool.aio_price] Skipping FR
2020-11-01 22:00:11 DEBUG (MainThread) [custom_components.nordpool.aio_price] Skipping NL
2020-11-01 22:00:11 DEBUG (MainThread) [custom_components.nordpool.aio_price] Skipping AT
2020-11-01 22:00:11 DEBUG (MainThread) [custom_components.nordpool.aio_price] Skipping BE
2020-11-01 22:00:11 DEBUG (MainThread) [custom_components.nordpool.aio_price] Skipping DE-LU
2020-11-01 22:00:11 DEBUG (MainThread) [custom_components.nordpool.aio_price] Skipping FR
2020-11-01 22:00:11 DEBUG (MainThread) [custom_components.nordpool.aio_price] Skipping NL
2020-11-01 22:00:11 DEBUG (MainThread) [custom_components.nordpool.aio_price] Skipping AT
2020-11-01 22:00:11 DEBUG (MainThread) [custom_components.nordpool.aio_price] Skipping BE
2020-11-01 22:00:11 DEBUG (MainThread) [custom_components.nordpool.aio_price] Skipping DE-LU
2020-11-01 22:00:11 DEBUG (MainThread) [custom_components.nordpool.aio_price] Skipping FR
2020-11-01 22:00:11 DEBUG (MainThread) [custom_components.nordpool.aio_price] Skipping NL
2020-11-01 22:00:11 DEBUG (MainThread) [custom_components.nordpool.sensor] called check_stuff
2020-11-01 22:00:11 DEBUG (MainThread) [custom_components.nordpool.sensor] NordpoolSensor _data_tomorrow is none, trying to fetch it.
2020-11-01 22:00:12 ERROR (MainThread) [homeassistant.util.logging] Exception in check_stuff when dispatching 'nordpool_update': ()
File "/config/custom_components/nordpool/sensor.py", line 404, in check_stuff
File "/config/custom_components/nordpool/sensor.py", line 356, in _update_current_price
File "/config/custom_components/nordpool/__init__.py", line 109, in today
File "/config/custom_components/nordpool/__init__.py", line 102, in _someday
2020-11-01 23:00:00 DEBUG (MainThread) [custom_components.nordpool] Called new_hr callback
2020-11-01 23:00:00 DEBUG (MainThread) [custom_components.nordpool.sensor] called check_stuff
2020-11-01 23:00:00 DEBUG (MainThread) [custom_components.nordpool.sensor] NordpoolSensor _data_tomorrow is none, trying to fetch it.
2020-11-01 23:00:00 ERROR (MainThread) [homeassistant.util.logging] Exception in check_stuff when dispatching 'nordpool_update': ()
File "/config/custom_components/nordpool/sensor.py", line 404, in check_stuff
File "/config/custom_components/nordpool/sensor.py", line 356, in _update_current_price
File "/config/custom_components/nordpool/__init__.py", line 109, in today
File "/config/custom_components/nordpool/__init__.py", line 102, in _someday
2020-11-02 00:00:00 DEBUG (MainThread) [custom_components.nordpool] Called new_hr callback
2020-11-02 00:00:00 DEBUG (MainThread) [custom_components.nordpool.sensor] called check_stuff
2020-11-02 00:00:00 DEBUG (MainThread) [custom_components.nordpool.sensor] NordpoolSensor _data_tomorrow is none, trying to fetch it.
2020-11-02 00:00:00 ERROR (MainThread) [homeassistant.util.logging] Exception in check_stuff when dispatching 'nordpool_update': ()

**Comment by Hellowlol** [comment]
Is this a issue?

**Comment by JaniAst** [comment]
Yes this is not solved yet. Happening randomly every 2-4 day.

**Comment by prilly-dev** [comment]
Same issue here, when firing it back up again price information is also wrong.

**Comment by Hellowlol** [comment]
Is lockup still a issue or can i close this?

**Comment by JaniAst** [comment]
Yes you can close this.

**Comment by akselaase** [comment]
This just happened to me tonight. I don't have more detailed logs than the traceback already reported unfortunately, but if it's likely to happen again I could turn on debug logging. Seems to be working properly again after a restart.

```py
2021-11-30 07:00:00 ERROR (MainThread) [homeassistant.util.logging] Exception in check_stuff when dispatching 'nordpool_update': ()
Traceback (most recent call last):
  File "/config/custom_components/nordpool/sensor.py", line 470, in check_stuff
    await self._update_current_price()
  File "/config/custom_components/nordpool/sensor.py", line 423, in _update_current_price
    data = await self._api.today(self._area, self._currency)
  File "/config/custom_components/nordpool/__init__.py", line 107, in today
    res = await self._someday(area, currency, "today")
  File "/config/custom_components/nordpool/__init__.py", line 100, in _someday
    return self._data.get(currency, {}).get(day, {}).get(area)
AttributeError: 'NoneType' object has no attribute 'get'
```
