### ISSUE TITLE
Unable to setup 0.15

### ISSUE THREAD

**Issue by bengtner** [custom-components/nordpool#425]
Unable to setup integration. After restarting HA I get the following message:
Logger: homeassistant.setup
Source: setup.py:475
First occurred: 19:20:19 (1 occurrences)
Last logged: 19:20:19

Unable to prepare setup for platform 'nordpool.sensor': Unable to set up component.

See enclosed log for more details.

## Version of the custom_component
0.15

## Homeassistant version
24.10.3

## Configuration

```

- platform: nordpool
    region: "SE4"
    VAT: false

```

## Describe the bug
Initialization for the component fails.

## Debug log

```
2024-10-20 19:20:19.695 ERROR (MainThread) [homeassistant.setup] Error during setup of component nordpool
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/setup.py", line 398, in _async_setup_component
result = await task
^^^^^^^^^^
File "/config/custom_components/nordpool/__init__.py", line 197, in async_setup
return await _dry_setup(hass, config)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/nordpool/__init__.py", line 179, in _dry_setup
tz=await dt_utils.async_get_time_zone("Europe/Stockholm"),
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'homeassistant.util.dt' has no attribute 'async_get_time_zone'
2024-10-20 19:20:19.727 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform 'nordpool.sensor': Unable to set up component.

```

**Comment by Hellowlol** [comment]
What ha version are you really using? The function is sats is missing is present in 24.10.3

**Comment by bengtner** [comment]
2024.10.3!

![image](https://github.com/user-attachments/assets/e076e27d-f60f-4b7b-b56a-bded611a1b41)

**Comment by bengtner** [comment]
Issue close. Problem solved once I updated HA.....
