### ISSUE TITLE
Setup failed after update til HAOS 2024.11.0

### ISSUE THREAD

**Issue by Bredum** [custom-components/nordpool#443]
Get error after update HAOS to version 2024.11.0

Logger: homeassistant.setup
Kilde: setup.py:334
Første forekomst: 22.10.25 (1 forekomster)
Senest logget: 22.10.25

Setup failed for custom integration 'nordpool': Unable to import component: No module named 'nordpool.base'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1031, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1011, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1071, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/nordpool/__init__.py", line 16, in <module>
    from .aio_price import AioPrices, InvalidValueException
  File "/config/custom_components/nordpool/aio_price.py", line 10, in <module>
    from nordpool.base import CurrencyMismatch
ModuleNotFoundError: No module named 'nordpool.base'

**Comment by oivindklausen** [comment]
I can confirm that, see the same

**Comment by AgentFalcon** [comment]
This is same as another posted issue. Just fixed it myself with as described in this comment:
https://github.com/custom-components/nordpool/issues/438#issuecomment-2454672058

Use File Editor add-on or similar to change the version and restart.

**Comment by vkempp** [comment]
Same issue here

**Comment by mario-pranjic** [comment]
Logger: homeassistant.core
Source: helpers/deprecation.py:222
First occurred: 10:42:06 PM (1 occurrences)
Last logged: 10:42:06 PM

Config was used from nordpool, this is a deprecated alias which will be removed in HA Core 2025.11. Use homeassistant.core_config.Config instead, please report it to the author of the 'nordpool' custom integration

**Comment by eddysteurs** [comment]
same problem but restore of 2024.10.4 did not solve the problem, same error, maybe problem on nordpool side?

**Comment by mario-pranjic-statnett** [comment]
@eddysteurs check workaround here: https://github.com/custom-components/nordpool/issues/438#issuecomment-2454672058

**Comment by tomsi62** [comment]
I have the same problem when I installed the new HA version 2024.11.0. Do you have some solutions?

**Comment by mario-pranjic** [comment]
@eddysteurs please check workaround https://github.com/custom-components/nordpool/issues/438#issuecomment-2454672058

**Comment by eddysteurs** [comment]
Workaround applied and working
Thx
Sent from my iPhone
Eddy Steurs


On 7 Nov 2024, at 08:18, Mario Pranjic ***@***.***> wrote:

﻿

@eddysteurs<https://github.com/eddysteurs> please check workaround #438 (comment)<https://github.com/custom-components/nordpool/issues/438#issuecomment-2454672058>

**Comment by henningpetersen** [comment]
https://github.com/custom-components/nordpool/issues/438#issuecomment-2454672058

Workaround applied and everything is working again.
Thanks. :-)

**Comment by Pajuris** [comment]
"nordpool>=0.2" changed to "nordpool==0.4.2". After HA restart no values on nordpool graphs. :(

2024.11.0 version.

**Comment by cagemaan** [comment]
> "nordpool>=0.2" changed to "nordpool==0.4.2". After HA restart no values on nordpool graphs. :(
> 
> 2024.11.0 version.

Yeah, i have the same issue here. Can see this in the log:
TypeError: not all arguments converted during string formatting

**Comment by Newspaperman57** [comment]
This is a duplicate of #438

**Comment by mortenx** [comment]
Error
Config flow could not be loaded: {"message":"Invalid handler specified"}

**Comment by MarcelAtSmartshore** [comment]
Quick fix was good. Looking forward to a final solution.

**Comment by Hellowlol** [comment]
Closing, duplicate.
