### ISSUE TITLE
Integration not loading in HA 2024.11.0

### ISSUE THREAD

**Issue by jacobwod** [custom-components/nordpool#444]
## Version of the custom_component
0.0.15

## Homeassistant version
Core 2024.11.0

## Describe the bug
After updating to the latest core today the integration fails to load. One warning and one error related to Nordpool are shown in the log. Looks like some changes to the underlying APIs in HA. 

## Debug log

```text
Logger: homeassistant.setup
Källa: setup.py:334
Inträffade först: 07:04:44 (1 händelser)
Senast loggade: 07:04:44

Setup failed for custom integration 'nordpool': Unable to import component: No module named 'nordpool.base'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1031, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1011, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1071, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/nordpool/__init__.py", line 16, in <module>
    from .aio_price import AioPrices, InvalidValueException
  File "/config/custom_components/nordpool/aio_price.py", line 10, in <module>
    from nordpool.base import CurrencyMismatch
ModuleNotFoundError: No module named 'nordpool.base'

---

Logger: homeassistant.core
Källa: helpers/deprecation.py:222
Inträffade först: 07:04:44 (2 händelser)
Senast loggade: 07:04:45

Config was used from nordpool, this is a deprecated alias which will be removed in HA Core 2025.11. Use homeassistant.core_config.Config instead, please report it to the author of the 'nordpool' custom integration
Config was used from ev_smart_charging, this is a deprecated alias which will be removed in HA Core 2025.11. Use homeassistant.core_config.Config instead, please report it to the author of the 'ev_smart_charging' custom integration

```

**Comment by jacobwod** [comment]
I attempted a downgrade to 2024.10.4 an re-downloading the integration from HACS. However, the error introduced in 2024.11.0 did prevail:

```text
Logger: homeassistant.setup
Källa: setup.py:334
Inträffade först: 07:16:45 (1 händelser)
Senast loggade: 07:16:45

Setup failed for custom integration 'nordpool': Unable to import component: No module named 'nordpool.base'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1007, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/nordpool/__init__.py", line 16, in <module>
    from .aio_price import AioPrices, InvalidValueException
  File "/config/custom_components/nordpool/aio_price.py", line 10, in <module>
    from nordpool.base import CurrencyMismatch
ModuleNotFoundError: No module named 'nordpool.base'
```

Perhaps the upgrade to 2024.11 changed some configuration, making a simple downgrade impossible. But I'd be interesting to find out if other encounter this problem in 2024.11.0.

**Comment by x5serv** [comment]
I have the exact same issue after upgrading to 2024.11.0.

**Comment by jacobwod** [comment]
Excellent @x5serv! Sorry about the duplicate. Closing.
