### ISSUE TITLE
Setup fails with "template value is None" after update to 0.0.3

### ISSUE THREAD

**Issue by fredrikbaberg** [custom-components/nordpool#65]
## Version of the custom_component

Version 0.0.3

## Configuration

```yaml

Configured using Integration, nothing in yaml.
Two instances, one for EUR and one for SEK since there were issues with SEK earlier. Both are for region SE3.

```

## Describe the bug
After update 0.0.3 the integration does not load, I get `Error while setting up nordpool platform for sensor`. See log below.
I did the install (and update) through HACS, may be useful information.

## Debug log

```text

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 198, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/nordpool/sensor.py", line 121, in async_setup_entry
    _dry_setup(hass, config, async_add_devices)
  File "/config/custom_components/nordpool/sensor.py", line 96, in _dry_setup
    sensor = NordpoolSensor(
  File "/config/custom_components/nordpool/sensor.py", line 178, in __init__
    self._ad_template = cv.template(self._ad_template)
  File "/usr/src/homeassistant/homeassistant/helpers/config_validation.py", line 554, in template
    raise vol.Invalid("template value is None")
voluptuous.error.Invalid: template value is None

```

**Comment by Hellowlol** [comment]
Delete both and set it up again. If it still fails enable debug logging and post it.

**Comment by fredrikbaberg** [comment]
It works after removing, restart (since that is what Home Assistant told me to do) and add again.
I'm just surprised that it broke after the update, did I miss a breaking change?

**Comment by Hellowlol** [comment]
Nope. I forgot to handle any missing templates for existing config flow.

**Comment by fredrikbaberg** [comment]
Ok. Closing this issue now since it works for me after remove/add. And now it should be possible for others to find the issue.

Thank you for the integration, by the way!

**Comment by vulgarsonic** [comment]
I have the same problem.
However, reinstalling does not help, this is the log output after reinstalling.

```
Logger: homeassistant.components.sensor
Source: custom_components/nordpool/sensor.py:277
Integration: Sensor (documentation, issues)
First occurred: 9:24:32 PM (2 occurrences)
Last logged: 9:24:32 PM

Error adding entities for domain sensor with platform nordpool
Error while setting up nordpool platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 314, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 505, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 530, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/nordpool/sensor.py", line 485, in async_added_to_hass
    await self.check_stuff()
  File "/config/custom_components/nordpool/sensor.py", line 446, in check_stuff
    self._update(today)
  File "/config/custom_components/nordpool/sensor.py", line 297, in _update
    self._average = self._calc_price(data.get("Average"))
  File "/config/custom_components/nordpool/sensor.py", line 277, in _calc_price
    price = template_value + value / _PRICE_IN[self._price_type] * (
TypeError: can only concatenate str (not "float") to str
```

**Comment by Hellowlol** [comment]
Your template evaluates to a string.
