### ISSUE TITLE
Error "adding entities for domain sensor with platform nordpool" after update to 0.0.3

### ISSUE THREAD

**Issue by vulgarsonic** [custom-components/nordpool#67]
## Version of the custom_component
0.0.3

## Configuration

```text
Configured in UI, no yaml.

```

## Describe the bug
The initial error was exactly as descrived in issue #65 .
However reinstalling does not fix my issue.
It results in the error below.

## Debug log

```text
Logger: homeassistant.components.sensor
Source: custom_components/nordpool/sensor.py:277
Integration: Sensor (documentation, issues)
First occurred: 9:24:32 PM (2 occurrences)
Last logged: 9:24:32 PM

Error adding entities for domain sensor with platform nordpool
Error while setting up nordpool platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 314, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 505, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 530, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/nordpool/sensor.py", line 485, in async_added_to_hass
    await self.check_stuff()
  File "/config/custom_components/nordpool/sensor.py", line 446, in check_stuff
    self._update(today)
  File "/config/custom_components/nordpool/sensor.py", line 297, in _update
    self._average = self._calc_price(data.get("Average"))
  File "/config/custom_components/nordpool/sensor.py", line 277, in _calc_price
    price = template_value + value / _PRICE_IN[self._price


```

**Comment by Hellowlol** [comment]
You havnt posted the log, the entire traceback or your config/settings.

**Comment by vulgarsonic** [comment]
You're right of course, I'll get back to you tomorrow.

**Comment by ivargj** [comment]
Hi! I'm having the same issue. 

Debug log: 
```
2021-02-26 01:27:23 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform nordpool
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 315, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 506, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 530, in add_to_platform_finish
await self.async_added_to_hass()
File "/config/custom_components/nordpool/sensor.py", line 486, in async_added_to_hass
await self.check_stuff()
File "/config/custom_components/nordpool/sensor.py", line 447, in check_stuff
self._update(today)
File "/config/custom_components/nordpool/sensor.py", line 306, in _update
formatted_prices = [
File "/config/custom_components/nordpool/sensor.py", line 307, in <listcomp>
self._calc_price(
File "/config/custom_components/nordpool/sensor.py", line 278, in _calc_price
price = template_value + value / _PRICE_IN[self._price_type] * (
TypeError: can only concatenate str (not "float") to str
``` 
Config: 
```
sensor:
  - platform: nordpool
    VAT: True
    currency: "EUR"
    region: "Oslo"
    precision: 3 
    price_type: kWh
    friendly_name: "Power"
    additional_costs: ""
```
Actually got a different error with the basic config: 
```
sensor:
  - platform: nordpool
    region: "Kr.sand"
```

```
2021-02-26 01:44:26 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform nordpool
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 315, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 506, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 530, in add_to_platform_finish
await self.async_added_to_hass()
File "/config/custom_components/nordpool/sensor.py", line 485, in async_added_to_hass
await self.check_stuff()
File "/config/custom_components/nordpool/sensor.py", line 443, in check_stuff
today = await self._api.today(self._area, self._currency)
File "/config/custom_components/nordpool/__init__.py", line 107, in today
res = await self._someday(area, currency, "today")
File "/config/custom_components/nordpool/__init__.py", line 97, in _someday
await self.update_today(None)
File "/config/custom_components/nordpool/__init__.py", line 78, in update_today
await self._update("today")
File "/config/custom_components/nordpool/__init__.py", line 69, in _update
data = await spot.hourly(end_date=dt)
File "/config/custom_components/nordpool/aio_price.py", line 260, in hourly
return await self.fetch(self.HOURLY, end_date, areas)
File "/config/custom_components/nordpool/aio_price.py", line 255, in fetch
raw = [self._parse_json(i, areas) for i in res]
File "/config/custom_components/nordpool/aio_price.py", line 255, in <listcomp>
raw = [self._parse_json(i, areas) for i in res]
File "/usr/local/lib/python3.8/site-packages/nordpool/elspot.py", line 37, in _parse_json
currency = data['currency']
KeyError: 'currency'
```

It works on v0.0.2 with this config: 
```
sensor:
  - platform: nordpool
    VAT: True
    currency: "EUR"
    region: "Oslo"
    precision: 3 
    price_type: kWh
    friendly_name: "Power"
```

**Comment by ivargj** [comment]
Oh, actually the latest version also works without the `additional_costs: ""` in the config: 
```
sensor:
  - platform: nordpool
    VAT: True
    currency: "EUR"
    region: "Oslo"
    precision: 3 
    price_type: kWh
    friendly_name: "Power"
```
So I guess it's something with how the empty `additional_costs` is handeled.

**Comment by Hellowlol** [comment]
The sensor will handle a missing template, it dont handle a incorrect one.

**Comment by vulgarsonic** [comment]
Unfortunately i have not had time to do more testing as iḿ away from home rolled back to 0.0.2 to get it working.
But my sensor was set up all through the GUI.
SE3, Euro, 2 decimals, price in cents, no VAT.

Can provide screenshot and logs as soon as i'm back.

**Comment by Xnygra** [comment]
> Unfortunately i have not had time to do more testing as iḿ away from home rolled back to 0.0.2 to get it working.
> But my sensor was set up all through the GUI.
> SE3, Euro, 2 decimals, price in cents, no VAT.
> 
> Can provide screenshot and logs as soon as i'm back.

Just had exactly the same, had to rollback to 0.0.2 to get it working again.

**Comment by Hellowlol** [comment]
Closing this there is nothing usefull to go on. Open new issue using the issue template with debug loggging.
