### ISSUE TITLE
Sensor not shoing up in HA

### ISSUE THREAD

**Issue by arva-zz** [custom-components/nordpool#81]
## Configuration

```yaml

sensor:
  - platform: nordpool
     VAT: True
     currency: "EUR"
     low_price_cutoff: 0.95
     region: "EE"
     precision: 3
     price_type: kWh
     friendly_name: "Power"
     additional_costs: ""
```

## Describe the bug

Home Assistant configuration was valid, but sensor did nor show up on first try. Now I see a sensor named "sensor.nordpool_kwh_ee_eur_3_095_02", but it's unaivalable: "This entity is currently unavailable and is an orphan to a removed, changed or dysfunctional integration or device."

## Debug log

```text

Logger: homeassistant.components.sensor
Source: custom_components/nordpool/sensor.py:277
Integration: Sensor (documentation, issues)
First occurred: 10:11:19 AM (2 occurrences)
Last logged: 10:11:19 AM

Error adding entities for domain sensor with platform nordpool
Error while setting up nordpool platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 587, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 697, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/nordpool/sensor.py", line 485, in async_added_to_hass
    await self.check_stuff()
  File "/config/custom_components/nordpool/sensor.py", line 446, in check_stuff
    self._update(today)
  File "/config/custom_components/nordpool/sensor.py", line 305, in _update
    formatted_prices = [
  File "/config/custom_components/nordpool/sensor.py", line 306, in <listcomp>
    self._calc_price(
  File "/config/custom_components/nordpool/sensor.py", line 277, in _calc_price
    price = template_value + value / _PRICE_IN[self._price_type] * (
TypeError: can only concatenate str (not "float") to str

```

**Comment by arva-zz** [comment]
Stuped me. I left additional costs "" in and tis caused the problem. When i commented the line out, everything works.
