### ISSUE TITLE
Can't use MWh unit

### ISSUE THREAD

**Issue by wjaceh** [custom-components/nordpool#9]
error:
`Sat Nov 02 2019 17:16:05 GMT+0200 (Eastern European Standard Time)
Update for sensor.nordpool_mwh_ee_eur_3_10_0 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 270, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 450, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/nordpool/sensor.py", line 349, in update
    self._update(today)
  File "/config/custom_components/nordpool/sensor.py", line 242, in _update
    self._average = self._calc_price(data.get("Average"))
  File "/config/custom_components/nordpool/sensor.py", line 229, in _calc_price
    price = value / _PRICE_IN[self._price_type] * (float(1 + self._vat))
ZeroDivisionError: float division by zero`

works with kWh

**Comment by Hellowlol** [comment]
Thanks, its a silly mistake. I never expected ppl to want the prices in MWh 😂 so I never tested that.

**Comment by wjaceh** [comment]
works. thank you!
