### ISSUE TITLE
Problem with setup the Nordpool sensor

### ISSUE THREAD

**Issue by markuska00** [custom-components/nordpool#93]
## Version of the custom_component
0.03

## Configuration

  - platform: nordpool
    VAT: True
    low_price_cutoff: 0.95
    region: "SE3"
    precision: 3
    price_type: kWh
    additional_costs: "{{0.0|float}}"

## Describe the bug
I can not get the Nordpool sensor to work.
The sensor appear but its emty and unavailable.

Add your logs here.

2021-12-15 12:44:22 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up nordpool platform for sensor
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity_platform.py", line 201, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity_platform.py", line 310, in async_add_entities
    await asyncio.gather(*tasks)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity_platform.py", line 481, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 521, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/home/homeassistant/.homeassistant/custom_components/nordpool/sensor.py", line 485, in async_added_to_hass
    await self.check_stuff()
  File "/home/homeassistant/.homeassistant/custom_components/nordpool/sensor.py", line 446, in check_stuff
    self._update(today)
  File "/home/homeassistant/.homeassistant/custom_components/nordpool/sensor.py", line 305, in _update
    formatted_prices = [
  File "/home/homeassistant/.homeassistant/custom_components/nordpool/sensor.py", line 306, in <listcomp>
    self._calc_price(
  File "/home/homeassistant/.homeassistant/custom_components/nordpool/sensor.py", line 277, in _calc_price
    price = template_value + value / _PRICE_IN[self._price_type] * (
TypeError: can only concatenate str (not "float") to str

**Comment by Hellowlol** [comment]
I have no idea why this is happening. Try setting up the sensor using the config page and not yaml. If that dont work you need to enable debug logging.  Try again and post the log here.

**Comment by markuska00** [comment]
I have tried setting the sensor with the config page. Same problem


Here is the log

Logger: homeassistant.components.sensor
Source: custom_components/nordpool/sensor.py:277
Integration: Sensor (documentation, issues)
First occurred: 2:10:08 (1 occurrences)
Last logged: 2:10:08

Error while setting up nordpool platform for sensor
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity_platform.py", line 201, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity_platform.py", line 310, in async_add_entities
    await asyncio.gather(*tasks)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity_platform.py", line 481, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 521, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/home/homeassistant/.homeassistant/custom_components/nordpool/sensor.py", line 485, in async_added_to_hass
    await self.check_stuff()
  File "/home/homeassistant/.homeassistant/custom_components/nordpool/sensor.py", line 446, in check_stuff
    self._update(today)
  File "/home/homeassistant/.homeassistant/custom_components/nordpool/sensor.py", line 297, in _update
    self._average = self._calc_price(data.get("Average"))
  File "/home/homeassistant/.homeassistant/custom_components/nordpool/sensor.py", line 277, in _calc_price
    price = template_value + value / _PRICE_IN[self._price_type] * (
TypeError: can only concatenate str (not "float") to str

**Comment by markuska00** [comment]
I have now got it to work with version 0.0.2

But the 0.0.3 still do not work for me


I have Home Assistant 0.116.3
Home Assistant Core

**Comment by ronseter** [comment]
Set additional_costs: 0.0 then it works

**Comment by MortenCB** [comment]
Is there an update on this issue?  I am unable to get it to work on latest HA and HACS and version 0.0.3 of nordpool.

**Comment by Hellowlol** [comment]
Nope, noone has provided a debug log. Its only the traceback. Just set up the sensors using the UI.

**Comment by tubalainen** [comment]
Looks like I am not alone :/
Sorry for making a duplicate issue here: https://github.com/custom-components/nordpool/issues/103

**Comment by Hellowlol** [comment]
Please try to copy paste the template you use for additional_costs into the template typo and check if the template is a string type.

**Comment by Hellowlol** [comment]
I’m gonna close this. The error is that the template isn’t a float as it’s supposed to be.
